name: Test and Coverage

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      EXCLUDE_TEST_TAG: moe.brianhsu.AudioOutputTest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Install packages
        run: |
          sudo apt-get update -yqq
          sudo apt-get install -yqq apt-transport-https curl gnupg
          echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
          echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
          sudo apt-get update
          sudo apt-get -y install sbt
          sudo apt-get -y install xorg-dev libglu1-mesa libgl1-mesa-dev xvfb libxinerama1 libxcursor1 libswt-gtk-4-java libswt-gtk-4-jni libxml2-utils bc zip gnupg

      - name: Setup Git Information
        run: |
          git config --global user.email "brianhsu.hsu+githu@gmail.com"
          git config --global user.name "GitHub Action"

      - name: Test and Coverage
        continue-on-error: true
        run: |
          ./distclean
          export SBT_OPTS="--enable-native-access=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED"
          xvfb-run --auto-servernum sbt coverage test coverageAggregate

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/test-reports-html/

      - name: Set Coverage rate for badges
        id: CoverageExport
        run: |
          echo "COVERAGE_RATE=$(xmllint --xpath "string(/scoverage/@branch-rate)" target/scala-3.3.2/scoverage-report/scoverage.xml)" >> $GITHUB_OUTPUT

      - name: Update Coverage badges
        run: |
          ./doc/images/generateCoverageBadage.sh ${{ steps.CoverageExport.outputs.COVERAGE_RATE }}

      - uses: EndBug/add-and-commit@v9
        with:
          add: 'doc/images/'
          message: Update coverage badge